taskkill /f /IM Dropbox.exe 2>%USERPROFILE%\temp.txt
taskkill /f /IM AthBtTray.exe 2>%USERPROFILE%\temp.txt
taskkill /f /IM btplayerctrl.exe 2>%USERPROFILE%\temp.txt
taskkill /f /IM BtvStack.exe 2>%USERPROFILE%\temp.txt
taskkill /f /IM  GoogleCrashHandler.exe 2>%USERPROFILE%\temp.txt
taskkill /f /IM  GoogleCrashHandler64.exe 2>%USERPROFILE%\temp.txt
taskkill /f /IM  armsvc.exe  2>%USERPROFILE%\temp.txt
taskkill /f /IM  iTunesHelper.exe 2>%USERPROFILE%\temp.txt
taskkill /f /IM  iPodService.exe 2>%USERPROFILE%\temp.txt
taskkill /f /IM  ONENOTEM.EXE 2>%USERPROFILE%\temp.txt
taskkill /f /IM  ClipMate.exe 2>%USERPROFILE%\temp.txt
taskkill /f /IM  AdobeARM.exe 2>%USERPROFILE%\temp.txt
taskkill /f /IM  jusched.exe 2>%USERPROFILE%\temp.txt
taskkill /f /IM  nvtray.exe 2>%USERPROFILE%\temp.txt
taskkill /f /IM  VDeck.exe 2>%USERPROFILE%\temp.txt
taskkill /f /IM  obexsrv.exe 2>%USERPROFILE%\temp.txt
taskkill /f /IM  nvxdsync.exe 2>%USERPROFILE%\temp.txt
taskkill /f /IM  nvvsvc.exe 2>%USERPROFILE%\temp.txt
taskkill /f /IM  FNPLicensingService64.exe 2>%USERPROFILE%\temp.txt
taskkill /f /IM  ZeroConfigService.exe 2>%USERPROFILE%\temp.txt
taskkill /f /IM  Launchy.exe 2>%USERPROFILE%\temp.txt